### ISSUE TITLE
Loading PDB files directly from Protein DB (enhancement)

### ISSUE THREAD

**Issue by tlskillman** [stevenvergenz/protein-viewer#10]
The open source app will have broader appeal if users can enter their PDB ID of interest and have it loaded directly from the Protein Data Bank (http://www.rcsb.org/pdb/home/home.do). Initially there would be no ribbon.

**Comment by tlskillman** [comment]
Since some of these models are large (too large?) the loading animation will be important. Or maybe a message saying too large to load.

**Comment by stevenvergenz** [comment]
Funny you should mention that, I actually just got the loading screen working! Well, mostly. It broke other things. I'll get it though lol

**Comment by stevenvergenz** [comment]
Done as of 3ae22a7
