### ISSUE TITLE
Unusual long-bonds in some atom-stick models

### ISSUE THREAD

**Issue by tlskillman** [stevenvergenz/protein-viewer#14]
I think this is from extra CONECT rows of data at the end of the .pdb file. 

As they do not appear to be important to the MVP, I suggest dropping those bonds unless they are Sodium to Sodium links.

**Comment by stevenvergenz** [comment]
Addressed in 2fdd99b. I've made it so manual bonds are not generated if they are longer than some fixed length. The current cutoff is 15 angstroms, because the worst offender (1J8H) had many bonds over 30, but the others were generally under this cutoff. We can tune this number as needed.
