### ISSUE TITLE
Add rest of ribbon models and align

### ISSUE THREAD

**Issue by tlskillman** [stevenvergenz/protein-viewer#15]
Finish creating the ribbon models for all molecules and aligning them with ball-stick models

**Comment by stevenvergenz** [comment]
Do any of the molecules (other than 2VAA) require rotation to be at a more natural angle to the floor?

**Comment by tlskillman** [comment]
Yes, all the rest need adjustments, rotations. Once rotated we may need to
scale, or translate, them all down a bit so that two helices making up the
groove are at about eye height.

**Comment by tlskillman** [comment]
BTW - 2VAA rotation looks great.

**Comment by stevenvergenz** [comment]
Okay, so that's the requirement? That the active site is at roughly eye level? It's currently set up so that the whole molecule is slightly taller than the user, in their default orientation.

Note too that the user will be able to adjust this orientation manually once I add controller support. If the ribbons don't take too long next week, that's next on the agenda.

**Comment by stevenvergenz** [comment]
I should say, it's scaled so that the entire molecule is within arms' reach of the average user, i.e. about 2m tall.

**Comment by tlskillman** [comment]
If the model is static in the room, most of the interesting details to
study are in the binding groove with the peptide that sits in it, so we
just need to be sure that is easy to look at up close at that area.

I expect the demo/user work flow will be to open a new protein in ribbon
mode, get oriented to the overall structural components (helices and
sheets), then turn on the atoms and bonds, look at how they define the
structure, then turn off the structure view and just study the atoms and
bonds.

If you have time to add controller-based movement of the model, then
initial orientation is no longer critical.

**Comment by tlskillman** [comment]
It's workable at this size, just may want to tweek it per my previous
comment.

**Comment by tlskillman** [comment]
Two PDB models that can be added if you have time: 1K5N and 3WPG.

**Comment by stevenvergenz** [comment]
Done as of c221e78.
