### ISSUE TITLE
Display of web accessible ProteinDB scientific documentation

### ISSUE THREAD

**Issue by tlskillman** [stevenvergenz/protein-viewer#8]
**Future MolVR feature request:** I've noticed that when I'm viewing a protein in MolVR, like 2VAA, I have been taking off my Vive headset to look up details about the protein in the PDB Database on my desktop machine (e.g., http://www.rcsb.org/pdb/explore/explore.do?structureId=2vaa).  It would be nice if the user could view that web page, and maybe browse others, while still in the Altspace MolVR room.

**Comment by stevenvergenz** [comment]
You can view that webpage, just use your private browser :)

**Comment by tlskillman** [comment]
Yeah, but  I was thinking about a view that everyone in the room could see.
Maybe a wall chart, like of 63 amino acids. Can you "hang" an image on a
wall. (future stuff).

**Comment by stevenvergenz** [comment]
Oh, yeah that's not a bad idea. There are several rooms with both 3d and 2d enclosures, it'd have to be set up in one of them. Put the model in the 3d, and its chemical index page in the 2d.

**Comment by tlskillman** [comment]
<<Note: I moved the new idea to a new issue>>

Yeah, something like that would be cool, and helpful to a discussion.

So one more idea for down the road... I've seen Youtube videos running on
screens inside Altspace. There is one particular video that maps out in one
6 min animation, the whole molecular process in a cell of chewing up
proteins into short peptides and then moving them out to the surface of a
cell for inspection by a T-cell.  If is focused more on orienting our
guests to the role of the molecule we are going to discuss, i.e., watch the
video, and then walking over to the 2VAA antigen presenting complex and
discussing in detail how the groove (helices) hold the peptide.  Here's the
video: https://www.youtube.com/watch?v=VPvCekgPwRI   (for the future).

**Comment by stevenvergenz** [comment]
Technically done?
