### ISSUE TITLE
View YouTube clips on a wall in the room (enhancement)

### ISSUE THREAD

**Issue by tlskillman** [stevenvergenz/protein-viewer#9]
I've seen Youtube videos running on screens inside Altspace. There is one particular video that maps out in one 6 min animation, the whole molecular process in a cell of chewing up proteins into short peptides and then moving them out to the surface of a cell for inspection by a T-cell.  If is focused more on orienting our guests to the role of the molecule we are going to discuss, i.e., watch the video, and then walking over to the 2VAA antigen presenting complex and discussing in detail how the groove (helices) hold the peptide.  Here's the video: https://www.youtube.com/watch?v=VPvCekgPwRI   (for the future).

**Comment by stevenvergenz** [comment]
I agree with this idea, but that's out of my hands as an SDK developer. We'll need to configure a room in altspace with everything we need.

**Comment by tlskillman** [comment]
Viewing YouTube videos inside the wall web browser meets this requirement.  Mark done!
